package listeners;

/* Panels */
import panels.BlackJackPanel;
import panels.ControlPanel;
import panels.StatusPanel;

/* States */
import states.GameStates;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Victor on 23-Dec-15.
 *
 * This class defines the object which listens for events on the "New Game" button.
 */
public class NewGameButtonListener implements ActionListener {

    /**
     * This function handles a click on the "New Game" button.
     * @param e The event generated by the click.
     */
    public void actionPerformed(ActionEvent e)
    {
        JButton but = (JButton)e.getSource(); // Get the button which dispatched the event
        ControlPanel cp = (ControlPanel)but.getParent(); // Get the control panel which contains the button
        BlackJackPanel bp = (BlackJackPanel)cp.getParent(); // Get the main panel which contains the control panel
        String uBet = cp.getBetTextFieldValue(); // Get the user-entered bet
        int uBetI; // The integer value of the user's bet
        StatusPanel sp = bp.getSp(); // Get the status panel for later use

        /* Validate the bet input */

        if (isValidInt(uBet)) // The bet is a valid integer
        {
            uBetI = Integer.parseInt(uBet); // Store the integer representation of the bet

            if (uBetI > 0) // The bet is a valid dollar amount
            {
                if (uBetI <= sp.getMoney()) // The user hasn't tried to bet more money than they have
                {
                    // Everything is OK - the bet is a valid integer, it is a valid dollar amount, and it isn't more money than they have

                    /* Handle the "New Game" event */
                    sp.setBet(uBetI); // Set the bet in the status panel
                    bp.updatePanel(GameStates.GAMESTART); // Send a "start game" message to the main panel
                }

                else // The user tried to bet more money than they have
                {
                    JOptionPane.showMessageDialog(bp, "Your bet value, \"" + uBet + "\", is larger than the amount of money in your possession!", "Invalid Bet", JOptionPane.ERROR_MESSAGE); // Display an error for the user
                }
            }

            else // Invalid bet amount (<= 0)
            {
                JOptionPane.showMessageDialog(bp, "Your bet value, \"" + uBet + "\", cannot be less than or equal to 0!", "Invalid Bet", JOptionPane.ERROR_MESSAGE); // Display an error for the user
            }
        }

        else // The bet is not a valid integer
        {
            JOptionPane.showMessageDialog(bp, "Your bet value, \"" + uBet + "\", is not a valid integer!", "Invalid Bet", JOptionPane.ERROR_MESSAGE); // Display an error for the user
        }
    }

    /**
     * Determines whether or not a string represents a valid integer.
     * @param toCheck The string to check.
     * @return True if the string can be safely converted to an integer, false otherwise.
     */
    private boolean isValidInt(String toCheck)
    {
        try
        {
            Integer.parseInt(toCheck); // Try to parse the string as an integer
            return true; // If we got here, the string was successfully parsed as an integer
        }

        catch (NumberFormatException nfe) // The string could not be parsed as an integer
        {
            return false; // Invalid integer
        }
    }
}
