package listeners;

import panels.BlackJackPanel;
import panels.ControlPanel;
import states.GameStates;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * This class listens for and handles click events dispatched by the "Stand" button
 */
public class StandButtonListener implements ActionListener {

    /**
     * This function handles the click event.
     * @param e The event generated by the click.
     */
    @Override
    public void actionPerformed(ActionEvent e)
    {
        // This method get the blackjack panel of the button that generated the
        // event, and uses the panel to resond if a player decides to "stand"
        JButton standButton = (JButton)e.getSource();
        ControlPanel cp = (ControlPanel)standButton.getParent();
        BlackJackPanel bp = (BlackJackPanel)cp.getParent(); 

        bp.updatePanel(GameStates.USTAND);
    }
}
