package listeners;

import panels.BlackJackPanel;
import panels.ControlPanel;
import states.GameStates;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Victor on 23-Dec-15.
 *
 * This class listens for and handles click events dispatched by the "Stand" button
 */
public class StandButtonListener implements ActionListener {

    /**
     * This function handles the click event.
     * @param e The event generated by the click.
     */
    @Override
    public void actionPerformed(ActionEvent e)
    {
        JButton standButton = (JButton)e.getSource(); // Get the button's source
        ControlPanel cp = (ControlPanel)standButton.getParent(); // Get the ControlPanel which contains the button
        BlackJackPanel bp = (BlackJackPanel)cp.getParent(); // Get the BlackJackPanel whcih contains the ControlPanel

        /* Update the panel with a "Stand" message */
        bp.updatePanel(GameStates.USTAND); // Send a "USTAND" message to the main panel
    }
}
